####服务启动端口号
#server:
#  port: 8200
####服务名称(服务注册到eureka名称)
#spring:
#  application:
#    name: app-mayikt-weixin
#  redis:
#    host: 120.78.137.82
#    port: 6379
#    pool:
#      max-idle: 100
#      min-idle: 1
#      max-active: 1000
#      max-wait: -1
####服务注册到eureka地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.170.129:8080/eureka
#
#
#####swagger相关配置
#swagger:
#  base-package: com.mayikt.weixin.service
#  title: SpringCloud2.x构建微服务电商项目-微信服务接口
#  description: 该项目“基于SpringCloud2.x构建微服务电商项目”
#  version: 1.1
#  terms-of-service-url: www.wxcs.cn
#  contact:
#    name: 比以往快10倍的登录方式
#    email: 416660553@qq.com

#logging:
#  level:
#    org.springframework.web: INFO
#    com.github.binarywang.demo.wx.mp: DEBUG
#    me.chanjar.weixin: DEBUG
#wx:
#  mp:
#    configs:
#      - appId: wx278c46143d54c73f #（一个公众号的appid）
#        secret: 759fddca9027becde10b1cc7b8b33d59 #（公众号的appsecret）
#        token: xxmit #（接口配置里的Token值）
#
#mayikt:
#  weixin:
#    registration:
#       code:
#       ###微信注册码消息
#        message:  您的注册码为:%s，请关注<a href="https://ke.qq.com/course/273548">腾讯课堂免费公开课</a>，欢迎观看97后架构师余老师的精品课程讲解。官方QQ群：<a href='https://jq.qq.com/?_wv=1027&k=5TVfAMF'>193086273</a>，期待你的加入，感谢！
#    ###默认提示消息
#    default:
#      registration:
#        code:
#          message: 您的消息，我们已经收到,会及时回复给您的!
###微信端口8200 做集群8201  8202  8203
###会员端口8300 做集群8301  8302  8303
###便于区分



#spring:
#  datasource:
#    url: jdbc:mysql://120.78.137.82:3306/meite_member?autoReconnect=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      connection-timeout: 30000
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 600000
#      pool-name: DatebookHikariCP
#      max-lifetime: 28740000
#      connection-test-query: SELECT 1
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: cn.xxm.mybatisplus.pojo
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 2
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 0
#    logic-not-delete-value: 1
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#  configuration:
#    call-setters-on-nulls: true
#    map-underscore-to-camel-case: true
#    cache-enabled: false